# Generated by Django 3.2.7 on 2021-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0003_alter_wpis_zawartosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='zawartosc',
            field=models.TextField(max_length=5000),
        ),
    ]
