# Generated by Django 3.2.7 on 2021-09-29 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0005_cryptocurrency_cryptohistorical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptohistorical',
            name='cryptocurrency',
        ),
        migrations.AddField(
            model_name='wpis',
            name='opis',
            field=models.TextField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
        migrations.DeleteModel(
            name='CryptoHistorical',
        ),
    ]
