# Generated by Django 3.2.7 on 2021-10-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0007_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='connected_news',
            field=models.ManyToManyField(related_name='wpis', to='Krypta.Wpis'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='whitepaper',
            field=models.URLField(null=True),
        ),
    ]
