# Generated by Django 3.2.7 on 2021-12-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0010_cryptocurrencyexchangemodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencyexchangemodel',
            name='date_of_transaction',
            field=models.DateField(),
        ),
    ]
