# Generated by Django 3.2.7 on 2021-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0012_alter_cryptocurrencyexchangemodel_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencyexchangemodel',
            name='date_of_transaction',
            field=models.DateField(),
        ),
    ]
