# Generated by Django 3.2.7 on 2021-12-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0013_alter_cryptocurrencyexchangemodel_date_of_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrencyexchangemodel',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=32),
        ),
    ]
