# Generated by Django 3.2.7 on 2021-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0014_cryptocurrencyexchangemodel_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencyexchangemodel',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Kupno'), ('SELL', 'Sprzedaż')], default='BUY', max_length=32),
        ),
    ]
