# Generated by Django 3.2.7 on 2021-12-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0015_alter_cryptocurrencyexchangemodel_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencyexchangemodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
