# Generated by Django 3.2.7 on 2021-12-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0016_alter_cryptocurrencyexchangemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(default='KRYPTO', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='connected_news',
            field=models.ManyToManyField(blank=True, related_name='wpis', to='Krypta.Wpis'),
        ),
    ]
