# Generated by Django 3.2.7 on 2021-12-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Krypta', '0017_auto_20211231_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'verbose_name': 'Kryptowaluta', 'verbose_name_plural': 'Kryptowaluty'},
        ),
        migrations.AlterModelOptions(
            name='cryptocurrencyexchangemodel',
            options={'verbose_name': 'Kupno i sprzedaż', 'verbose_name_plural': 'Kupno i sprzedaż'},
        ),
        migrations.AlterModelOptions(
            name='wpis',
            options={'verbose_name': 'Wpis', 'verbose_name_plural': 'Wpisy'},
        ),
    ]
